"""
Data Mapper - Chinese/English name mappings for Star Citizen trading
Based on official community localization (星际公民汉化组 global.ini)
"""

SYSTEM_ZH = {
    "Stanton": "斯坦顿",
    "Pyro": "派罗",
    "Nyx": "尼克斯",
}

PLANET_ZH = {
    "ArcCorp": "弧光星",
    "Hurston": "赫斯顿",
    "Crusader": "十字军",
    "MicroTech": "微科星",
    "Pyro V": "派罗V",
    "Bloom": "布卢姆",
    "Terminus": "终点",
    # Moons
    "Cellin": "赛琳",
    "Daymar": "戴玛尔",
    "Yela": "耶拉",
    "Aberdeen": "阿伯丁",
    "Arial": "艾瑞尔",
    "Magda": "玛格达",
    "Ita": "依塔",
    "Lyria": "莉瑞雅",
    "Wala": "瓦菈",
    "Calliope": "卡利俄佩",
    "Clio": "克利俄",
    "Euterpe": "欧忒耳佩",
    "Delamar": "德拉玛",
}

TERMINAL_ZH_MAP = {
    # --- Stanton: ArcCorp (弧光星) R&R Stations ---
    "ARC-L1": "弧-L1 广袤森林站",
    "ARC-L2": "弧-L2 活力小径站",
    "ARC-L3": "弧-L3 摩登快车站",
    "ARC-L4": "弧-L4 黯淡幽谷站",
    "ARC-L5": "弧-L5 黄色核心站",
    # --- Stanton: ArcCorp Locations ---
    "Area 18": "18区",
    "Area18": "18区",
    "Baijini Point": "百济尼点",
    "ArcCorp Mining Area 045": "弧光045采矿区",
    "ArcCorp Mining Area 048": "弧光048采矿区",
    "ArcCorp Mining Area 056": "弧光056采矿区",
    "ArcCorp Mining Area 061": "弧光061采矿区",
    "ArcCorp Mining Area 141": "弧光141采矿区",
    "ArcCorp Mining Area 157": "弧光157采矿区",
    "ArcCorp 141": "弧光141采矿区",
    "ArcCorp 157": "弧光157采矿区",
    "Humboldt Mines": "洪堡矿站",
    # --- Stanton: Hurston (赫斯顿) R&R Stations ---
    "HUR-L1": "赫-L1 绿色林地站",
    "HUR-L2": "赫-L2 坚贞梦想站",
    "HUR-L3": "赫-L3 雷霆快车站",
    "HUR-L4": "赫-L4 旋律领域站",
    "HUR-L5": "赫-L5 高速路线站",
    # --- Stanton: Hurston Locations ---
    "Lorville": "罗威尔",
    "Everus Harbor": "埃弗勒斯港",
    "HDMS-Anderson": "HDMS-安德森站",
    "HDMS-Bezdek": "HDMS-贝兹德克站",
    "HDMS-Edmond": "HDMS-埃得蒙德站",
    "HDMS-Hadley": "HDMS-哈德利站",
    "HDMS-Hahn": "HDMS-哈恩站",
    "HDMS-Lathan": "HDMS-莱森站",
    "HDMS-Norgaard": "HDMS-诺加德站",
    "HDMS-Oparei": "HDMS-奥派雷站",
    "HDMS-Perlman": "HDMS-佩尔曼站",
    "HDMS-Pinewood": "HDMS-派恩伍德站",
    "HDMS-Ryder": "HDMS-莱德站",
    "HDMS-Stanhope": "HDMS-斯坦霍普站",
    "HDMS-Thedus": "HDMS-泰德斯",
    "HDMS-Woodruff": "HDMS-伍德拉夫站",
    # --- Stanton: Crusader (十字军) R&R Stations ---
    "CRU-L1": "十-L1 雄心伟梦站",
    "CRU-L4": "十-L4 轻浅田野站",
    "CRU-L5": "十-L5 美丽峡谷站",
    # --- Stanton: Crusader Locations ---
    "GrimHEX": "六角湾",
    "Grim Hex": "六角湾",
    "Port Olisar": "奥丽莎港",
    "Seraphim Station": "塞拉芬站",
    "Benson Mining Outpost": "本森采矿前哨站",
    "Bountiful Harvest Hydroponics": "丰收水培种植站",
    "Brio's Breaker Yard": "布里奥的拆船场",
    "Kudre Ore": "库德雷矿井",
    "Deakins Research Outpost": "迪金斯科研前哨站",
    "Hickes Research Outpost": "希克斯研究站",
    "Gallete Family Farms": "加莱特家庭种植站",
    "R&D Kiosko": "研发基斯科",
    # --- Stanton: MicroTech (微科星) R&R Stations ---
    "MIC-L1": "微-L1 浅边站",
    "MIC-L2": "微-L2 长林站",
    "MIC-L3": "微-L3 无尽奇幻旅程站",
    "MIC-L4": "微-L4 红色十字路口站",
    "MIC-L5": "微-L5 现代伊卡洛斯站",
    # --- Stanton: MicroTech Locations ---
    "New Babbage": "新巴贝奇",
    "Port Tressler": "特雷斯勒港",
    "Bud's Growery": "巴德种植园",
    "Orinth": "奥林斯",
    "Astimedar": "阿斯提梅达",
    "K&J Catechin": "K&J儿茶素站",
    "Terra Gateway": "泰拉星门",
    # --- Pyro ---
    "Ruin Station": "废墟站",
    "Orbituary": "轨道墓场",
    "Rat's Nest": "鼠巢",
    "Verne": "凡尔纳",
    "Pyro Gateway": "派罗星门",
    "Seer's Canyon": "先知峡谷",
    "Spark": "火花站",
    "Bloom": "布卢姆",
    "Terminus": "终点站",
    "Pyro V": "派罗V",
    "Patch City": "补丁城",
    "Last Landings": "最后的着陆点",
    "Bullock's Reach": "布洛克之域",
    "Kinder Plots": "金德地块",
    "Sacren's Plot": "萨克林地块",
    "Dudley & Daughters": "达德利父子公司",
    "Rod's Fuel": "罗德燃料站",
    "Starlight Service Station": "星光服务站",
    "Atlas Space Force": "阿特拉斯太空军",
    # --- Nyx ---
    "Stanton Gateway": "斯坦顿星门",
    "Nyx Gateway": "尼克斯星门",
    "Levski": "列夫斯基",
    "PSS Alpha": "人民服务站阿尔法",
    "People's Service Station Alpha": "人民服务站阿尔法",
    "PSS Delta": "人民服务站德尔塔",
    "People's Service Station Delta": "人民服务站德尔塔",
    "PSS Theta": "人民服务站西塔",
    "People's Service Station Theta": "人民服务站西塔",
    "PSS Lambda": "人民服务站兰姆达",
    "People's Service Station Lambda": "人民服务站兰姆达",
    # --- General / Shop Names ---
    "TDD": "贸易发展部",
    "Trade and Development": "贸易发展部",
    "CBD": "中央商务区",
    "Admin": "指挥部",
    "Cargo Center": "货运中心",
    "Refinery Ore Sales": "精炼矿石销售",
    "Wikelo": "威克洛商场",
    "PlatinumBay": "白金湾",
    "Platinum Bay": "白金湾",
}

COMMODITY_ZH_MAP = {
    # === Metals (金属) ===
    "Tungsten": "钨", "Tungsten (Ore)": "钨矿石",
    "Gold": "金", "Gold (Ore)": "金矿石",
    "Iron": "铁", "Iron (Ore)": "铁矿石",
    "Copper": "铜", "Copper (Ore)": "铜矿石",
    "Aluminum": "铝", "Aluminum (Ore)": "铝矿石",
    "Titanium": "钛", "Titanium (Ore)": "钛矿石",
    "Cobalt": "钴",
    "Tin": "锡", "Tin (Ore)": "锡矿石",
    "Mercury": "汞",
    "Steel": "钢铁",
    # === Refined Minerals (精炼矿物) ===
    "Laranite": "砬兰石", "Laranite (Raw)": "砬兰石(原矿)",
    "Agricium": "艾格瑞金属", "Agricium (Ore)": "艾格瑞矿石",
    "Beryl": "绿柱石", "Beryl (Raw)": "绿柱石(原矿)",
    "Bexalite": "贝沙电气石", "Bexalite (Raw)": "贝沙电气石(原矿)",
    "Hephaestanite": "火神石", "Hephaestanite (Raw)": "火神石(原矿)",
    "Taranite": "塔兰导电石", "Taranite (Raw)": "塔兰导电石(原矿)",
    "Corundum": "刚玉", "Corundum (Raw)": "刚玉(原矿)",
    "Diamond": "钻石", "Diamond (Raw)": "钻石(原矿)",
    "Diamond Laminate": "钻石层压板",
    "Quartz": "石英", "Quartz (Raw)": "石英(原矿)",
    "Borase": "波射石", "Borase (Ore)": "波射矿石",
    "Aphorite": "紫钠水晶", "Aphorite (Raw)": "紫钠水晶(原矿)",
    "Dolivine": "暗橄榄石", "Dolivine (Raw)": "暗橄榄石(原矿)",
    "Hadanite": "哈丹水晶", "Hadanite (Raw)": "哈丹水晶(原矿)",
    "Quantainium": "量子矿物", "Quantainium (Raw)": "量子矿物(原矿)",
    # === Non-metals (非金属) ===
    "Silicon": "硅", "Silicon (Raw)": "硅原矿",
    "Carbon": "碳",
    # === Alloys & Processed (合金/加工品) ===
    "Atlasium": "巨神合金",
    "Dymantium": "代曼合金",
    "Bioplastic": "生物塑料",
    "DynaFlex": "高韧材料",
    "Omnapoxy": "环氧脂",
    "Carbon-Silk": "碳绸",
    "Compboard": "电路板",
    "Thermalfoam": "热泡沫塑料",
    "Neograph": "新石墨",
    "Xa'Pyen": "夏潘合金",
    "Silnex": "高级航空陶瓷",
    # === Gases (气体) ===
    "Hydrogen": "氢", "Hydrogen Fuel": "氢燃料",
    "Helium": "氦",
    "Nitrogen": "氮",
    "Methane": "甲烷",
    "Quantum Fuel": "量子燃料",
    "Astatine": "砹",
    "Chlorine": "氯气",
    "Fluorine": "氟",
    "Iodine": "碘",
    "Neon": "\u201c霓虹\u201d",
    "Argon": "氩气",
    "Potassium": "钾",
    "Tritium": "氚",
    "Ammonia": "氨",
    # === Contraband/Vice (违禁品) ===
    "Stims": "斯酊姆烟草",
    "Distilled Spirits": "蒸馏酒精",
    "Maze": "\u201c迷宫\u201d",
    "SLAM": "\u201c冠军\u201d",
    "WiDoW": "\u201c黑寡妇\u201d",
    "E'tam": "艾坦药草",
    "Altruciatoxin": "幻云",
    "Revenant Tree Pollen": "亡魂树花粉",
    "Revenant Pod": "亡魂果荚",
    "Uncut SLAM": "未加工的\u201c冠军\u201d",
    # === Agriculture (农业) ===
    "Agricultural Supplies": "农业用品",
    "Agricultural Goods": "农业产品",
    "Fresh Food": "新鲜食品",
    "Processed Food": "加工食品",
    "Human Food Bars": "人类食品棒",
    "Pitambu": "皮坦布果",
    "Prota": "普罗塔菌",
    "Degnous Root": "德古尼斯藻根",
    "Golden Medmon": "黄金麦德蒙果",
    "Sunset Berries": "日落浆果",
    "Ranta Dung": "兰塔有机粪便",
    "Gasping Weevil Eggs": "窒息象鼻虫卵",
    "Sulfermoss": "硫黄苔藓",
    "Fotiascrub": "福蒂雅种荚",
    "Blue Bilva": "蓝木橘",
    "Oza": "奥扎橘",
    "Jumping Limes": "跳跳橙",
    "Spiral": "月果(螺旋果)",
    "Pingala": "宾伽罗种子",
    "Heart of the Woods": "\u201c森林之心\u201d",
    "Decaripod": "德卡利孢囊",
    # === Medical (医疗) ===
    "Medical Supplies": "医疗用品",
    "MedPens": "医疗笔",
    "OxyPens": "氧气笔",
    "LifeCure MedSticks": "疗生医疗棒",
    # === Industrial (工业) ===
    "Construction Materials": "建筑材料",
    "Scrap": "废料",
    "Waste": "垃圾",
    "Waste Rock": "岩石",
    "Mixed Mining": "混合矿石",
    "Inert Materials": "惰性物质",
    "Organics": "有机物",
    "Recycled Material Composite": "再生复合材料",
    "Crude Oil": "原油",
    "Coal": "煤",
    # === Other Commodities ===
    "Riccite": "愈金", "Riccite (Ore)": "愈金矿",
    "Osoian Hides": "奥索安皮革",
    "Marok Gem": "马罗克宝石",
    "Kopion Horn": "科普恩角",
    "Lindinium": "林迪尼姆",
    "Torite": "托岩", "Torite (Ore)": "托岩矿",
    "Savrilium": "萨夫里利姆", "Savrilium Ore": "萨夫里利姆矿",
    "Partillium": "Partillium",
    "Stileron": "斯蒂勒龙",
    "Aslarite": "阿斯拉岩",
    "Ouratite": "欧拉岩",
    "Beradom": "贝拉多姆",
    "Glacosite": "格拉科岩",
    "Feynmaline": "费恩马林",
    "Carinite": "卡里岩",
    "Jaclium": "贾克里姆",
    "Sadaryx": "萨达里克斯",
    "Pressurized Ice": "压缩冰",
    "Raw Ice": "原冰",
    "Ammunition": "弹药",
    "Detatrine": "德塔特林",
    "CryoPod": "冷冻舱",
    "Souvenirs": "纪念品",
    "Party Favors": "聚会礼品",
    "Fireworks": "烟花",
    "Consumer Goods": "消费品",
    "Diluthermex": "稀热树脂",
    "Dopple": "多普勒",
    "Eriesium": "铍",
    "Europium": "铕",
    "Lithium": "锂",
    "Magnesium": "镁",
    "Neodymium": "钕",
    "Phosphorus": "磷",
    "Polonium": "钋",
    "Praseodymium": "镨",
    "Rubidium": "铷",
    "Selenium": "硒",
    "Sodium": "钠",
    "Tellurim": "碲",
    "Thorium": "钍",
    "Uranium": "铀",
    "Xenon": "氙",
    "Boron": "硼",
    "Arsenic": "砷",
    "Anti-Hydrogen": "反氢",
    "AntiHydrogen": "反氢",
    "Cadmium Allinide": "亚胺镉",
    "Acryliplex": "亚克力络合物复合材料",
    "Lycara": "莱护材料",
    "Mala": "玛拉毒素",
    "Nereus": "涅瑞斯",
    "Sarilus": "沙鲁斯",
    "Zeta-Prolanide": "Z-普罗兰化合物",
    "MobyGlass": "mobyGlass 个人电脑",
    "Diamond Laminate": "钻石层压板",
    "Altruciatoxin Unprocessed": "亡魂树花粉",
    "Agricultural Supplies": "农业用品",
    "CK13-GID Seeds": "CK13-GID 混合种子",
    "HLX99 Hyperprocessors": "HLX99 疯牛处理器",
    "Osoian Hides": "奥索安皮革",
    "RS1 Odyssey Spacesuits": "RS1 奥德赛飞行服",
    "Redfin Energy Modulator": "红鳍能量调制器",
    "Audio-Visual Equipment": "视听设备",
    "DCSR2": "DCSR2",
    "SCR": "SCR",
}


def get_terminal_zh(en_name: str, en_nickname: str = "", en_station: str = "",
                    en_planet: str = "", en_system: str = "") -> str:
    """Translate terminal name to Chinese."""
    if en_name in TERMINAL_ZH_MAP:
        return TERMINAL_ZH_MAP[en_name]
    if en_nickname and en_nickname in TERMINAL_ZH_MAP:
        return TERMINAL_ZH_MAP[en_nickname]
    candidates = [en_name, en_nickname, en_station]
    for cand in candidates:
        if not cand:
            continue
        for key in sorted(TERMINAL_ZH_MAP.keys(), key=len, reverse=True):
            if key.lower() in cand.lower():
                return TERMINAL_ZH_MAP[key]
    return en_name


def get_commodity_zh(en_name: str) -> str:
    """Translate commodity name to Chinese."""
    return COMMODITY_ZH_MAP.get(en_name, en_name)


def format_location_zh(name: str, nickname: str, station: str,
                       planet: str, system: str) -> str:
    """Generate Chinese location description."""
    zh_name = get_terminal_zh(name, nickname, station, planet, system)
    parts = [zh_name]
    if planet:
        zh_planet = PLANET_ZH.get(planet, planet)
        parts.append(f"[{zh_planet}]")
    zh_system = SYSTEM_ZH.get(system, system)
    parts.append(f"({zh_system})")
    return " ".join(parts)
