"""
Data Mapper - Chinese/English name mappings for Star Citizen trading
Synced from:
  1. 星际公民汉化组 global.ini (Gitee: StarCitizen_CN/sc_l10n_zh_s)
  2. ParaTranz project 8340 (https://paratranz.cn/projects/8340)
"""

SYSTEM_ZH = {
    "Nyx": "尼克斯",
    "Pyro": "派罗",
    "Stanton": "斯坦顿",
}

PLANET_ZH = {
    "Aberdeen": "阿伯丁",
    "ArcCorp": "弧光星",
    "Arial": "艾瑞尔",
    "Bloom": "盛放星",
    "Calliope": "卡利俄佩",
    "Cellin": "赛琳",
    "Clio": "克利俄",
    "Crusader": "十字军",
    "Daymar": "戴玛尔",
    "Delamar": "德拉玛(Delamar)",
    "Euterpe": "欧忒耳佩",
    "Hurston": "赫斯顿",
    "Ita": "依塔",
    "Lyria": "莉瑞雅",
    "Magda": "玛格达",
    "MicroTech": "微科公司",
    "Monox": "莫诺克斯",
    "Pyro IV": "派罗 IV",
    "Pyro V": "派罗 V",
    "Pyro VI": "派罗 VI",
    "Terminus": "端点星",
    "Wala": "瓦菈",
    "Yela": "耶拉",
}

TERMINAL_ZH_MAP = {
    # --- Rest stops (global.ini: Stanton{n}_L{n}) ---
    "ARC-L1": "弧-L1 广袤森林站",
    "ARC-L2": "弧-L2 活力小径站",
    "ARC-L3": "弧-L3 摩登快车站",
    "ARC-L4": "弧-L4 黯淡幽谷站",
    "ARC-L5": "弧-L5 黄色核心站",
    "CRU-L1": "十-L1 雄心伟梦站",
    "CRU-L4": "十-L4 轻浅田野站",
    "CRU-L5": "十-L5 美丽峡谷站",
    "HUR-L1": "赫-L1 绿色林地站",
    "HUR-L2": "赫-L2 坚贞梦想站",
    "HUR-L3": "赫-L3 雷霆快车站",
    "HUR-L4": "赫-L4 旋律领域站",
    "HUR-L5": "赫-L5 高速路线站",
    "MIC-L1": "微-L1 浅边站",
    "MIC-L2": "微-L2 长林站",
    "MIC-L3": "微-L3 无尽奇幻旅程站",
    "MIC-L4": "微-L4 红色十字路口站",
    "MIC-L5": "微-L5 现代伊卡洛斯站",
    # --- Major landing zones (global.ini) ---
    "Area 18": "18区",
    "Area18": "18区",
    "Lorville": "罗威尔",
    "New Babbage": "新巴贝奇",
    "Orison": "奥里森",
    "Levski": "列夫斯基",
    "Port Olisar": "奥丽莎港",
    "Grim Hex": "六角湾",
    "GrimHEX": "六角湾",
    # --- Space stations (global.ini) ---
    "Baijini Point": "拜基尼太空站",
    "Everus Harbor": "埃弗勒斯港",
    "Port Tressler": "特雷斯勒太空站",
    "Seraphim Station": "炽天使空间站",
    "Seraphim": "炽天使空间站",
    "UEX Station": "利夫斯登车站",
    # --- Gateways (global.ini) ---
    "Nyx Gateway": "尼克斯星门",
    "Pyro Gateway": "派罗星门",
    "Stanton Gateway": "斯坦顿星门",
    "Terra Gateway": "泰拉星门",
    # --- PSS (global.ini: People's Service Station) ---
    "People's Service Station Alpha": "人民服务空间站 阿尔法",
    "People's Service Station Delta": "人民服务空间站 德尔塔",
    "People's Service Station Lambda": "人民服务空间站 拉姆达",
    "People's Service Station Theta": "人民服务空间站 西塔",
    "PSS Alpha": "人民服务空间站 阿尔法",
    "PSS Delta": "人民服务空间站 德尔塔",
    "PSS Lambda": "人民服务空间站 拉姆达",
    "PSS Theta": "人民服务空间站 西塔",
    # --- HDMS (global.ini: Stanton1_HurDynMining) ---
    "HDMS-Anderson": "HDMS-安德森站",
    "HDMS-Bezdek": "HDMS-贝兹德克站",
    "HDMS-Edmond": "HDMS-埃得蒙德站",
    "HDMS-Hadley": "HDMS-哈德利站",
    "HDMS-Hahn": "HDMS-哈恩站",
    "HDMS-Lathan": "HDMS-莱森站",
    "HDMS-Norgaard": "HDMS-诺加德站",
    "HDMS-Oparei": "HDMS-奥派雷站",
    "HDMS-Perlman": "HDMS-佩尔曼站",
    "HDMS-Pinewood": "HDMS-派恩伍德站",
    "HDMS-Ryder": "HDMS-莱德站",
    "HDMS-Stanhope": "HDMS-斯坦霍普站",
    "HDMS-Thedus": "HDMS-赛达斯站",
    "HDMS-Woodruff": "HDMS-伍德拉夫站",
    # --- Shubin (global.ini: Stanton{n}_Shubin) ---
    "Shubin Mining Facility SAL-2": "舒宾矿业设施 SAL-2",
    "Shubin Mining Facility SAL-5": "舒宾矿业设施 SAL-5",
    "Shubin Mining Facility SCD-1": "舒宾采矿设施 SCD-1",
    "Shubin Mining Facility SM0-10": "舒宾矿业设施 SM0-10",
    "Shubin Mining Facility SM0-13": "舒宾矿业设施 SM0-13",
    "Shubin Mining Facility SM0-18": "舒宾矿业设施 SM0-18",
    "Shubin Mining Facility SM0-22": "舒宾矿业设施 SM0-22",
    "Shubin Mining Facility SMCa-6": "舒宾加工设施 SMCa-6",
    "Shubin Mining Facility SMCa-8": "舒宾加工设施 SMCa-8",
    # --- ArcCorp Mining (global.ini: Stanton3b_ArcCorp) ---
    "ArcCorp Mining Area 045": "弧光045采矿区",
    "ArcCorp Mining Area 048": "弧光048采矿区",
    "ArcCorp Mining Area 056": "弧光056采矿区",
    "ArcCorp Mining Area 061": "弧光061采矿区",
    "ArcCorp Mining Area 141": "弧光141采矿区",
    "ArcCorp Mining Area 157": "弧光157采矿区",
    "ArcCorp 045": "弧光045采矿区",
    "ArcCorp 048": "弧光048采矿区",
    "ArcCorp 056": "弧光056采矿区",
    "ArcCorp 061": "弧光061采矿区",
    "ArcCorp 141": "弧光141采矿区",
    "ArcCorp 157": "弧光157采矿区",
    # --- Rayari Research (global.ini: Stanton{n}_Rayari) ---
    "Rayari Anvik Research Outpost": "拉亚利-安维克研究站",
    "Rayari Cantwell Research Outpost": "拉亚利-坎特韦尔研究站",
    "Rayari Deltana Research Outpost": "拉亚利-德尔塔纳研究站",
    "Rayari Kaltag Research Outpost": "拉亚利-卡尔塔格研究站",
    "Rayari McGrath Research Outpost": "拉亚利-麦格拉思研究站",
    # --- Outposts with global.ini translations ---
    "Benson Mining Outpost": "本森采矿前哨站",
    "Bountiful Harvest Hydroponics": "丰收水培种植站",
    "Brio's Breaker Yard": "布里奥的拆船场",
    "Bud's Growery": "巴德种植园",
    "Deakins Research Outpost": "迪金斯科研前哨站",
    "Hickes Research Outpost": "希克斯研究站",
    "Gallete Family Farms": "加莱特家庭种植站",
    "Humboldt Mines": "洪保德矿站",
    "Kudre Ore": "库德雷矿井",
    "Loveridge Mineral Reserve": "洛维里奇矿站",
    "Nuen Waste Management": "努恩废物管理中心",
    "Terra Mills Hydrofarm": "泰拉磨坊水培种植站",
    "Tram & Myers Mining": "泰姆&迈尔斯矿站",
    "Samson & Son's Salvage Center": "参孙父子回收站",
    "Devlin Scrap and Salvage": "德夫林废品回收站",
    "Rustville": "锈镇",
    "Orbituary": "轨道讣闻站",
    "Ruin Station": "报废空间站",
    "Checkmate": "将死空间站",
    "Patch City": "补丁城",
    "Rat's Nest": "鼠巢空间站",
    "Dudley & Daughters": "达德利父女空间站",
    "Endgame": "残局空间站",
    "Gaslight": "煤气灯空间站",
    "Megumi Refueling": "惠加油空间站",
    "Rod's Fuel 'N Supplies": "罗德燃料补给站",
    "Starlight Service Station": "星光服务站",
    "Starlight Service": "星光服务站",
    "Sacren's Plot": "萨克伦领地",
    "Seer's Canyon": "先觉者峡谷",
    "Jackson's Swap": "杰克逊交换站",
    "Dinger's Depot": "丁格仓库",
    "Frostbite": "冻伤哨站",
    "Jumptown": "跃动小镇",
    "Outpost 54": "前哨站 54",
    "Paradise Cove": "天堂湾",
    "Private Property": "私人财产",
    "Raven's Roost": "渡鸦栖",
    "Scarper's Turn": "斯卡珀转角",
    "Shady Glen": "荫谷",
    "Slowburn Depot": "缓燃仓库",
    "Watcher's Depot": "守望仓库",
    "Prospect Depot": "勘探仓库",
    "Feo Canyon Depot": "费奥峡谷仓库",
    "Gray Gardens Depot": "灰园仓库",
    "Chawla's Beach": "乔拉海滩",
    "Canard View": "鸭嘴岬",
    "Fallow Field": "休耕田",
    "Bueno Ravine": "布埃诺峡谷",
    "Ashland": "灰地",
    "Sunset Mesa": "日落台地",
    "Last Landings": "终陆镇",
    "Windfall": "横财站",
    "Shepherd's Rest": "牧人栖所",
    "The Yard": "船坞",
    "Yang's Place": "杨氏驻地",
    "Zephyr": "西风站",
    "Arid Reach": "旱域",
    "Blackrock Exchange": "黑岩交易所",
    "Bullock's Reach": "犍牛原",
    "Carver's Ridge": "卡弗山脊",
    "Frigid Knot": "冻结点",
    "Goner's Deal": "冈纳交易站",
    "Kabir's Post": "卡比尔哨站",
    "Kinder Plots": "容善镇",
    "Narena's Rest": "纳雷纳栖所",
    "Ostler's Claim": "奥斯勒领地",
    "Prophet's Peak": "先知峰",
    "Rough Landing": "迫降场",
    "Stag's Rut": "雄鹿发情场",
    "Pickers Field": "拾荒场",
    "Rappel": "绕降站",
    "Astors Clearing": "阿斯特空地",
    "Dunboro": "邓伯勒",
    "Weeping Cove": "泣湾",
    "The Golden Riviera": "黄金海岸",
    "The Necropolis": "墓地",
    "The Orphanage": "孤儿院",
    "Covalex Distribution Centre S4DC05": "科瓦莱克斯配送中心 S4DC05",
    "INS Jericho": "INS 杰里科军港",
    "INS Jericho - Pyro Gateway": "INS 杰里科军港",
    "NT-999-XX": "NT-999-XX",
    "NT-999-XXII": "NT-999-XXII",
    # --- Lorville areas (global.ini) ---
    "CBD": "中央商务区",
    "CBD - Central Business District - Lorville": "中央商务区 - 罗威尔",
    "L19 Residences - Metro Center - Lorville": "L19 居住区 - 罗威尔",
    "Hurston Dynamics Showcase": "赫斯顿动力展示厅",
    "Maria Pure of Heart": "玛利亚纯洁之心",
    # --- Orison areas (global.ini) ---
    "Covalex Shipping - Providence Platform - Orison": "科瓦莱克斯货运 - 普罗维登斯平台 - 奥里森",
    "Orison Municipal Services": "奥里森市政服务",
    "Orison General Hospital": "奥里森综合医院",
    "NovaworX Industries": "诺瓦沃克斯工业",
    "Crusader Discovery Center": "十字军探索中心",
    "Providence Platform": "普罗维登斯平台",
    # --- New Babbage areas (global.ini) ---
    "Aspire Grand": "志远大厦",
    "The Commons": "市民广场",
    "NBIS": "NBIS航站楼",
    "MicroTech Planetary Services": "微科星球公务部",
    "Shubin Interstellar": "舒宾星际",
    # --- Shops & Services ---
    "Platinum Bay": "白金湾",
    "PlatinumBay": "白金湾",
    "Casaba Outlet": "卡萨巴奥特莱斯",
    "Dumper's Depot": "达珀仓库",
    "Cubby Blast": "卡比爆破",
    "Live Fire Weapons": "实弹武器店",
    "Refinery Ore Sales": "精炼矿石销售",
    "Refinery Shop": "精炼商店",
    "TDD": "贸易发展部",
    "Trade and Development": "贸易发展部",
    "Buy and Fly": "即买即飞",
    "Traveler Rentals": "旅行者租赁",
    "Vantage Rentals": "优势租赁",
    "Regal Luxury Rentals": "豪华租赁",
    "New Deal": "新交易",
    "CenterMass": "中心质量",
    "Ellroy's": "埃罗伊",
    "Guns": "枪械",
    "Armor": "护甲",
    "Pharmacy": "药房",
    "Medical Shop": "医疗商店",
    "Ship Weapons": "舰船武器",
    "Ship Parts": "舰船配件",
    "Weapons and Armor": "武器与护甲",
    "FPS Shop": "FPS 商店",
    "Aloprats": "阿洛普拉斯",
    "Ore Sales": "矿石销售",
    "Sundries": "杂货",
    "Tools & Supplies": "工具与补给",
    "Clothing Shop": "服装店",
    "Filtered Water": "过滤水",
    "Station Convenience": "站点便利店",
    "Unique Quality": "独特品质",
    "Gear Up": "装备站",
    "Ready To Trade": "随时交易",
    "Sharp Shooters": "神射手",
    "KC Trending": "KC 潮流",
    "Skutters": "斯库特斯",
    "Technotic": "科技疯",
    "Grey's Market": "格雷市场",
    "Grand Barter": "大宗交易",
    "Conscientious Objects": "自觉之物",
    "Cordry's": "科德里",
    "Hats & More": "帽子与更多",
    "Laying Roots": "扎根",
    "Nyx Nax": "尼克斯纳克斯",
    "Teach's": "蒂奇",
    "Wake Up": "醒醒",
    "Near Beer": "近啤酒",
    "Shelf Stable": "耐储存",
    "Feed The People": "喂饱人民",
    "Noodle Bar": "面条吧",
    "Noodles": "面条",
    "Noodle": "面条",
    "Hot Dogs": "热狗",
    "Burrito Bar": "卷饼吧",
    "Pizza": "披萨",
    "Juice Bar": "果汁吧",
    "Coffee To Go": "外带咖啡",
    "Fried Grubs": "油炸虫子",
    "Torpedo Burrito": "鱼雷卷饼",
    "Twyn's Sandwiches": "特温三明治",
    "Omega Pro": "欧米茄专业",
    "Whammer's": "锤击",
    "Carafi": "卡拉菲",
    "Seanuts": "海坚果",
    "Rust": "锈蚀",
    "Scrap": "废料",
    "Reclamation and Disposal": "回收处理",
    "Orinth": "奥林斯",
    # --- Other ---
    "Spark": "火花站",
    "Verne": "凡尔纳",
    "Wikelo": "维克洛",
    "Wikelo Emporium Dasi Station": "维克洛商场 达西站",
    "Wikelo Emporium Kinga Station": "维克洛商场 金加站",
    "Wikelo Emporium Selo Station": "维克洛商场 塞洛站",
    "Astimedar": "阿斯提梅达",
    "Atlas Space Force": "阿特拉斯太空军",
    "AydoExpress Hub": "爱快快递枢纽",
    "K&J Catechin": "K&J儿茶素站",
    "R&D Kiosko": "研发基斯科",
    "Bloom": "盛放星",
    "Delamar": "德拉玛",
    "Terminus": "端点星",
    "Pyro V": "派罗 V",
    "Refinement Center": "精炼中心",
    "Refinement Processing": "精炼加工",
    "Landing Services": "降落服务",
    "Landing Service": "降落服务",
    "Cargo Center": "货运中心",
    "Cargo Services": "货运服务",
    "Cargo Supplies": "货运补给",
    "Crusader Showroom": "十字军展厅",
    "Cousin Crow's": "鸦兄",
    "Tammany and Sons": "塔马尼父子",
    "Security Tower": "安全塔",
    "Personal Weapons": "个人武器",
    "Equipment Contested Zone": "争议区装备",
    "Locker Room": "更衣室",
    "Maintenance Room": "维护室",
    "Makau": "马考",
    "Aparelli": "阿帕雷利",
    "Astro Armada": "星际舰队",
    "IO North Tower": "IO北塔",
    "Factory Line": "工厂线",
    "Garcia's Greens": "加西亚蔬果",
    "Brentworth Pharmacy": "布伦特沃斯药房",
    "Kel-To": "凯尔托",
    "Hurston Dynamics": "赫斯顿动力",
    "Providence Surplus": "普罗维登斯剩余物资",
    "Covalex": "科瓦莱克斯",
    "Fresh Food": "新鲜食品",
    "Human Food Bars": "人类食品棒",
    "Processed Food": "加工食品",
    "Medical Supplies": "医疗用品",
    "Distilled Spirits": "蒸馏酒精",
    "Construction Materials": "建筑材料",
    "Construction Material": "建筑材料",
    "Stims": "斯酊姆烟草",
    "Souvenirs": "纪念品",
    "Party Favors": "聚会礼品",
    "Fireworks": "烟花",
    "Luminalia Gift": "光节礼物",
    # --- space_station_name / outpost_name variants (UEX API uses shorter forms) ---
    "Deakins Research": "迪金斯科研前哨站",
    "Green Imperial Housing Exchange": "六角湾",
    "Hickes Research": "希克斯研究站",
    "Picker's Field": "拾荒场",
}

COMMODITY_ZH_MAP = {
    "Acryliplex": "亚克力络合物复合材料",
    "Agricium": "艾格瑞金属",
    "Agricium (Ore)": "艾格瑞矿石",
    "Agricultural Goods": "农业产品",
    "Agricultural Supplies": "农业用品",
    "Altruciatoxin": "梸树毒",
    "Altruciatoxin Unprocessed": "亡魂树花粉",
    "Aluminum": "铝",
    "Aluminum (Ore)": "铝矿石",
    "Ammonia": "氨",
    "Ammunition": "实弹武器",
    "Anti-Hydrogen": "反氢",
    "AntiHydrogen": "反氢",
    "Aphorite": "紫钠水晶",
    "Aphorite (Raw)": "紫钠水晶（粗制）",
    "Argon": "氩",
    "Arsenic": "砷",
    "Aslarite": "阿斯莱晶体",
    "Astatine": "砹",
    "Atlasium": "巨神合金",
    "Audio-Visual Equipment": "视听设备",
    "Beradom": "冰蓝珀",
    "Beryl": "绿柱石",
    "Beryl (Raw)": "绿柱石（粗制）",
    "Bexalite": "贝沙电气石",
    "Bexalite (Raw)": "贝沙电气石（粗制）",
    "Bioplastic": "生物塑料",
    "Blue Bilva": "蓝木橘",
    "Borase": "波射石",
    "Borase (Ore)": "波射矿石",
    "Boron": "硼",
    "CK13-GID Seeds": "CK13-GID 混合种子",
    "Cadmium Allinide": "亚胺镉",
    "Carbon": "碳",
    "Carbon-Silk": "碳绸",
    "Carinite": "科力晶",
    "Chlorine": "氯气",
    "Coal": "煤",
    "Cobalt": "钴",
    "Compboard": "电路板",
    "Construction Materials": "建筑材料",
    "Consumer Goods": "消费品",
    "Copper": "铜",
    "Copper (Ore)": "铜矿石",
    "Corundum": "刚玉",
    "Corundum (Raw)": "刚玉（粗制）",
    "Crude Oil": "原油",
    "CryoPod": "冷冻舱",
    "DCSR2": "DCSR2",
    "Decaripod": "德卡利孢囊",
    "Degnous Root": "德古尼斯藻根",
    "Detatrine": "得他啶",
    "Diamond": "钻石",
    "Diamond (Raw)": "钻石（粗制）",
    "Diamond Laminate": "钻石层压板",
    "Diluthermex": "稀热树脂",
    "Distilled Spirits": "蒸馏酒精",
    "Dolivine": "暗橄榄石",
    "Dolivine (Raw)": "暗橄榄石（粗制）",
    "Dopple": "多普勒",
    "Dymantium": "代曼合金",
    "DynaFlex": "高韧材料",
    "E'tam": "艾坦药草(E'tam)",
    "Eriesium": "铍",
    "Europium": "铕",
    "Feynmaline": "熵瞬晶",
    "Fireworks": "烟花",
    "Fluorine": "氟",
    "Fotiascrub": "福蒂雅种荚",
    "Fresh Food": "新鲜食品",
    "Gasping Weevil Eggs": "窒息象鼻虫卵",
    "Glacosite": "冰碛棉",
    "Gold": "金",
    "Gold (Ore)": "金矿石",
    "Golden Medmon": "黄金麦德蒙果",
    "HLX99 Hyperprocessors": "HLX99 疯牛处理器",
    "Hadanite": "哈丹水晶",
    "Hadanite (Raw)": "哈丹水晶（粗制）",
    "Heart of the Woods": "\u201c森林之心\u201d",
    "Helium": "氦",
    "Hephaestanite": "火神石",
    "Hephaestanite (Raw)": "火神石（粗制）",
    "Human Food Bars": "人类食品棒",
    "Hydrogen": "氢",
    "Hydrogen Fuel": "氢燃料",
    "Inert Materials": "惰性物质",
    "Iodine": "碘",
    "Iron": "铁",
    "Iron (Ore)": "铁矿石",
    "Jaclium": "杰金",
    "Jumping Limes": "跳跳橙",
    "Kopion Horn": "寇骈犬角",
    "Laranite": "砬兰石",
    "Laranite (Raw)": "砬兰石（粗制）",
    "LifeCure MedSticks": "生疗医疗棒",
    "Lindinium": "林登金",
    "Lithium": "锂",
    "Lycara": "莱护材料",
    "Magnesium": "镁",
    "Mala": "玛拉毒素",
    "Marok Gem": "啼笑鸟胃石",
    "Maze": "\u201c迷宫\u201d",
    "MedPens": "医疗笔",
    "Medical Supplies": "医疗用品",
    "Mercury": "汞",
    "Methane": "甲烷",
    "Mixed Mining": "混合矿石",
    "MobyGlass": "mobyGlass 个人电脑",
    "Neodymium": "钕",
    "Neograph": "新石墨",
    "Neon": "\u201c霓虹\u201d",
    "Nereus": "涅瑞斯",
    "Nitrogen": "氮",
    "Omnapoxy": "环氧脂",
    "Organics": "有机物",
    "Osoian Hides": "奥索安皮革",
    "Ouratite": "欧拉特烃",
    "OxyPens": "氧气笔",
    "Oza": "奥扎橘",
    "Partillium": "帕缇利气",
    "Party Favors": "聚会礼品",
    "Phosphorus": "磷",
    "Pingala": "宾伽罗",
    "Pitambu": "皮坦布果",
    "Polonium": "钋",
    "Potassium": "钾",
    "Praseodymium": "镨",
    "Pressurized Ice": "高压冰",
    "Processed Food": "加工食品",
    "Prota": "普罗塔菌",
    "Quantainium": "量子矿",
    "Quantainium (Raw)": "量子矿（粗制）",
    "Quantum Fuel": "量子燃料",
    "Quartz": "石英",
    "Quartz (Raw)": "石英（粗制）",
    "RS1 Odyssey Spacesuits": "RS1 奥德赛飞行服",
    "Ranta Dung": "兰塔有机粪便",
    "Raw Ice": "原冰",
    "Recycled Material Composite": "再生复合材料",
    "Redfin Energy Modulator": "红鳍能量调制器",
    "Revenant Pod": "亡魂果荚",
    "Revenant Tree Pollen": "亡魂树花粉",
    "Riccite": "愈金",
    "Riccite (Ore)": "愈金矿石",
    "Rubidium": "铷",
    "SCR": "标准商用橡胶",
    "SLAM": "\u201c冠军\u201d",
    "Sadaryx": "萨达瑞晶",
    "Sarilus": "沙鲁斯",
    "Savrilium": "萨维里金属",
    "Savrilium Ore": "萨夫里利姆矿",
    "Scrap": "废料",
    "Selenium": "硒",
    "Silicon": "硅",
    "Silicon (Raw)": "硅原矿",
    "Silnex": "高级航空陶瓷",
    "Sodium": "钠",
    "Souvenirs": "纪念品",
    "Spiral": "月果(螺旋果)",
    "Steel": "钢",
    "Stileron": "稀钛铁",
    "Stims": "斯酊姆烟草",
    "Sulfermoss": "硫黄苔藓",
    "Sunset Berries": "日落浆果",
    "Taranite": "塔兰导电石",
    "Taranite (Raw)": "塔兰导电石（粗制）",
    "Tellurim": "碲",
    "Thermalfoam": "热泡沫塑料",
    "Thorium": "钍",
    "Tin": "锡",
    "Tin (Ore)": "锡矿石",
    "Titanium": "钛",
    "Titanium (Ore)": "钛矿石",
    "Torite": "托瑞特金属",
    "Torite (Ore)": "托瑞特金属矿石",
    "Tritium": "氚",
    "Tungsten": "钨",
    "Tungsten (Ore)": "钨矿石",
    "Uncut SLAM": "未加工的\u201c冠军\u201d",
    "Uranium": "铀",
    "Waste": "垃圾",
    "Waste Rock": "岩石",
    "WiDoW": "\u201c黑寡妇\u201d",
    "Xa'Pyen": "夏潘合金",
    "Xenon": "氙",
    "Zeta-Prolanide": "Z-普罗兰化合物",
    # --- v3.13.0: 补全 UEX API 全部货物中文映射 ---
    "AcryliPlex Composite": "亚克力络合物复合材料",
    "Amioshi Plague": "阿米什瘟疫",
    "Apoxygenite": "脱氧岩",
    "Aslarite (Raw)": "阿斯莱晶体（粗制）",
    "Atacamite": "铜绿矾",
    "Audio Visual Equipment": "视听设备",
    "CK13-GID Seed Blend": "CK13-GID 混合种子",
    "Carinite (Pure)": "科力晶（精制）",
    "Cave Kopion Horn": "洞穴寇骈犬角",
    "Cobalt (Raw)": "钴（粗制）",
    "Construction Material Pebbles": "建筑材料碎石",
    "Construction Material Rubble": "建筑材料碎砖",
    "Construction Material Salvage": "建筑材料回收料",
    "Decari Pod": "德卡利孢囊",
    "Elespo": "俄列斯泼",
    "Freeze": "冻滞",
    "Glow": "光热",
    "HexaPolyMesh Coating": "六聚网涂层",
    "Irradiated Kopion Horn": "辐射寇骈犬角",
    "Jaclium (Ore)": "杰金矿石",
    "Jahlium": "贾利姆",
    "Janalite": "贾纳石",
    "Krypton": "氪",
    "Lastaphrene": "拉斯塔弗伦",
    "Lifecure Medsticks": "生疗医疗棒",
    "Lindinium Ore": "林登金矿",
    "Luminalia Gift": "光节礼物",
    "Lunes": "月银",
    "Molina Mold Samples": "莫利纳霉菌样本",
    "Molina Mold Treatment": "莫利纳霉菌处理剂",
    "Molina Ventilation Filters": "莫利纳通风过滤器",
    "Ouratite (Raw)": "欧拉特烃（粗制）",
    "Redfin Energy Modulators": "红鳍能量调制器",
    "Saldynium (Ore)": "萨尔迪尼姆矿",
    "Ship Ammunition": "实弹武器弹药",
    "Ship Ammunition - Size 1": "实弹武器弹药 - 1号",
    "Ship Ammunition - Size 2": "实弹武器弹药 - 2号",
    "Ship Ammunition - Size 3": "实弹武器弹药 - 3号",
    "Ship Ammunition - Size 4": "实弹武器弹药 - 4号",
    "Ship Ammunition - Size 5": "实弹武器弹药 - 5号",
    "Ship Ammunition - Size 6": "实弹武器弹药 - 6号",
    "Ship Ammunition - Size 7": "实弹武器弹药 - 7号",
    "Ship Decoy Countermeasures": "舰载诱饵反制系统",
    "Ship Noise Countermeasures": "舰载噪声反制系统",
    "Stileron (Raw)": "稀钛铁（粗制）",
    "Stone Bug Shell": "石虫壳",
    "Tellurium": "碲",
    "Thrust": "\u201c猛冲\u201d",
    "Tundra Kopion Horn": "苔原寇骈犬角",
    "Wuotan Seed": "乌坦种子",
    "Year of the Dog Envelope": "狗年红包",
    "Year of the Monkey Envelope": "猴年红包",
    "Year of the Pig Envelope": "猪年红包",
    "Year of the Rat Envelope": "鼠年红包",
    "Year of the Rooster Envelope": "鸡年红包",
    "Zip": "\u201c滋滋\u201d",
}


def get_terminal_zh(en_name: str, en_nickname: str = "", en_station: str = "",
                    en_planet: str = "", en_system: str = "") -> str:
    """Translate terminal name to Chinese."""
    if en_name in TERMINAL_ZH_MAP:
        return TERMINAL_ZH_MAP[en_name]
    if en_nickname and en_nickname in TERMINAL_ZH_MAP:
        return TERMINAL_ZH_MAP[en_nickname]
    candidates = [en_name, en_nickname, en_station]
    for cand in candidates:
        if not cand:
            continue
        for key in sorted(TERMINAL_ZH_MAP.keys(), key=len, reverse=True):
            if key.lower() in cand.lower():
                return TERMINAL_ZH_MAP[key]
    return en_name


def get_commodity_zh(en_name: str) -> str:
    """Translate commodity name to Chinese."""
    return COMMODITY_ZH_MAP.get(en_name, en_name)


VEHICLE_ZH_MAP = {
    # --- Origin ---
    "100i": "100i",
    "125a": "125a",
    "135c": "135c",
    "300i": "300i",
    "315p": "315p 探索者",
    "325a": "325a 战斗机",
    "350r": "350r 竞速者",
    "400i": "400i 探索者",
    "600i Executive Edition": "600i 行政版",
    "600i Explorer": "600i 探索者",
    "600i Touring": "600i 旅行版",
    "85X": "85X",
    # --- RSI ---
    "890 Jump": "890 跃动",
    "Aurora Mk I CL": "极光 CL",
    "Aurora Mk I ES": "极光 ES",
    "Aurora Mk I LN": "极光 LN",
    "Aurora Mk I LX": "极光 LX",
    "Aurora Mk I MR": "极光 MR",
    "Aurora Mk I SE": "极光 SE",
    "Aurora Mk II": "极光 Mk II",
    "Constellation Andromeda": "仙女座",
    "Constellation Aquila": "天鹰座",
    "Constellation Phoenix": "凤凰座",
    "Constellation Phoenix Emerald": "凤凰座 翡翠版",
    "Constellation Taurus": "金牛座",
    "Zeus Mk II CL": "宙斯 Mk II CL",
    "Zeus Mk II ES": "宙斯 Mk II ES",
    "Zeus Mk II MR": "宙斯 Mk II MR",
    "Hull A": "货轮 A",
    "Hull B": "货轮 B",
    "Hull C": "货轮 C",
    "Hull D": "货轮 D",
    "Hull E": "货轮 E",
    "Polaris": "北极星",
    "Idris-M": "伊德里斯-M",
    "Idris-P": "伊德里斯-P",
    "Javelin": "标枪",
    "Perseus": "英仙座",
    "Pioneer": "先驱者",
    "Liberator": "解放者",
    "Starlancer BLD": "星际枪骑兵 BLD",
    "Starlancer MAX": "星际枪骑兵 MAX",
    "Starlancer TAC": "星际枪骑兵 TAC",
    "Mantis": "螳螂",
    # --- Aegis ---
    "Avenger Stalker": "复仇者 追猎",
    "Avenger Titan": "复仇者 泰坦",
    "Avenger Titan Renegade": "复仇者 泰坦 叛逆者",
    "Avenger Warlock": "复仇者 战巫",
    "Eclipse": "日食",
    "Gladiator": "角斗士",
    "Gladius": "短剑",
    "Gladius Pirate": "短剑 海盗版",
    "Gladius Valiant": "短剑 勇敢者",
    "Hammerhead": "锤头鲨",
    "Hammerhead Best In Show Edition": "锤头鲨 最佳展示版",
    "Hawk": "猎鹰",
    "Reclaimer": "回收者",
    "Reclaimer Best In Show Edition": "回收者 最佳展示版",
    "Redeemer": "救赎者",
    "Retaliator": "报复者",
    "Retaliator Bomber": "报复者 轰炸型",
    "Retaliator Cargo Module - Bow": "报复者 货舱模块 - 舰首",
    "Retaliator Cargo Module - Stern": "报复者 货舱模块 - 舰尾",
    "Retaliator Dropship Front Module": "报复者 突击舰模块 - 前部",
    "Retaliator Living Front Module": "报复者 居住模块 - 前部",
    "Retaliator Living Rear Module": "报复者 居住模块 - 后部",
    "Retaliator Torpedo Module \u2013 Bow": "报复者 鱼雷模块 - 舰首",
    "Retaliator Torpedo Module \u2013 Stern": "报复者 鱼雷模块 - 舰尾",
    "Sabre": "军刀",
    "Sabre Comet": "军刀 彗星",
    "Sabre Firebird": "军刀 火鸟",
    "Sabre Peregrine": "军刀 游隼",
    "Sabre Raven": "军刀 渡鸦",
    "Vanguard Harbinger": "先锋 亡灵",
    "Vanguard Hoplite": "先锋 重装步兵",
    "Vanguard Sentinel": "先锋 哨兵",
    "Vanguard Warden": "先锋 看守者",
    "Vulcan": "伏尔甘",
    "Nautilus": "鹦鹉螺",
    "Nautilus Solstice Edition": "鹦鹉螺 至日版",
    "Apollo Medivac": "阿波罗 医疗",
    "Apollo Triage": "阿波罗 分诊",
    "L-21 Wolf": "L-21 狼",
    "L-22 Alpha Wolf": "L-22 头狼",
    "Asgard": "阿斯加德",
    "Salvation": "救赎",
    # --- Anvil ---
    "Arrow": "箭矢",
    "Ballista": "弩炮",
    "Ballista Dunestalker": "弩炮 沙丘猎手",
    "Ballista Snowblind": "弩炮 雪盲",
    "C8 Pisces": "双鱼座 C8",
    "C8R Pisces Rescue": "双鱼座 C8R 救援",
    "C8X Pisces Expedition": "双鱼座 C8X 远征",
    "F7A Hornet Mk I": "大黄蜂 F7A Mk I",
    "F7A Hornet Mk II": "大黄蜂 F7A Mk II",
    "F7C Hornet Mk I": "大黄蜂 F7C Mk I",
    "F7C Hornet Mk II": "大黄蜂 F7C Mk II",
    "F7C Hornet Wildfire Mk I": "大黄蜂 F7C 野火 Mk I",
    "F7C-M Super Hornet Heartseeker Mk I": "超级大黄蜂 F7C-M 寻心者 Mk I",
    "F7C-M Super Hornet Mk I": "超级大黄蜂 F7C-M Mk I",
    "F7C-M Super Hornet Mk II": "超级大黄蜂 F7C-M Mk II",
    "F7C-R Hornet Tracker Mk I": "大黄蜂 F7C-R 追踪者 Mk I",
    "F7C-R Hornet Tracker Mk II": "大黄蜂 F7C-R 追踪者 Mk II",
    "F7C-S Hornet Ghost Mk I": "大黄蜂 F7C-S 幽灵 Mk I",
    "F7C-S Hornet Ghost Mk II": "大黄蜂 F7C-S 幽灵 Mk II",
    "F8C Lightning": "闪电 F8C",
    "F8C Lightning Executive Edition": "闪电 F8C 行政版",
    "Hurricane": "飓风",
    "Terrapin": "水龟",
    "Terrapin Medic": "水龟 医疗",
    "Valkyrie": "女武神",
    "Valkyrie Liberator Edition": "女武神 解放者版",
    "Legionnaire": "军团兵",
    "Pitbull": "斗牛犬",
    "Spartan": "斯巴达",
    "Centurion": "百夫长",
    # --- Crusader ---
    "A1 Spirit": "精神 A1",
    "C1 Spirit": "精神 C1",
    "E1 Spirit": "精神 E1",
    "A2 Hercules Starlifter": "大力神 A2",
    "C2 Hercules Starlifter": "大力神 C2",
    "M2 Hercules Starlifter": "大力神 M2",
    "Mercury Star Runner": "墨丘利 星际快运船",
    "Starfarer": "星际远航者",
    "Starfarer Gemini": "星际远航者 双子座",
    "Genesis Starliner": "创世纪 星际客机",
    # --- Drake ---
    "Buccaneer": "掠夺者",
    "Cutlass Black": "黑弯刀",
    "Cutlass Black Best In Show Edition": "黑弯刀 最佳展示版",
    "Cutlass Blue": "蓝弯刀",
    "Cutlass Red": "红弯刀",
    "Cutlass Steel": "钢弯刀",
    "Caterpillar": "毛虫",
    "Caterpillar Best In Show Edition": "毛虫 最佳展示版",
    "Caterpillar Pirate Edition": "毛虫 海盗版",
    "Corsair": "海盗船",
    "Cutter": "切割者",
    "Cutter Rambler": "切割者 漫游者",
    "Cutter Scout": "切割者 侦察兵",
    "Dragonfly Black": "蜻蜓 黑色",
    "Dragonfly Yellowjacket": "蜻蜓 黄夹克",
    "Herald": "信使",
    "Mule": "骡子",
    "MULE": "骡子",
    "Vulture": "秃鹫",
    "Kraken": "海妖",
    "Kraken Privateer": "海妖 私掠者",
    "Guardian": "守卫",
    "Guardian MX": "守卫 MX",
    "Guardian QI": "守卫 QI",
    "Golem": "魔像",
    "Golem Ox": "魔像 牛",
    "Stingray": "魔鬼鱼",
    "Stinger": "毒刺",
    # --- MISC ---
    "Freelancer": "自由枪骑兵",
    "Freelancer DUR": "自由枪骑兵-DUR",
    "Freelancer MAX": "自由枪骑兵-MAX",
    "Freelancer MIS": "自由枪骑兵-MIS",
    "Prospector": "勘探者",
    "Reliant Kore": "信赖 基础",
    "Reliant Mako": "信赖 新闻",
    "Reliant Sen": "信赖 科考",
    "Reliant Tana": "信赖 武装",
    "Razor": "剃刀",
    "Razor EX": "剃刀 EX",
    "Razor LX": "剃刀 LX",
    "Starlite": "星光",
    "Fortune": "财富",
    "Hull A": "货轮 A",
    "Hull B": "货轮 B",
    "Hull C": "货轮 C",
    "Hull D": "货轮 D",
    "Hull E": "货轮 E",
    "Expanse": "广阔号",
    "Odyssey": "奥德赛",
    "Endeavor": "奋进号",
    "Endeavor Fuel Bay Pod": "奋进号 燃料舱吊舱",
    "Endeavor General Research Pod": "奋进号 通用研究吊舱",
    "Endeavor Landing Bay Pod": "奋进号 停机舱吊舱",
    "Endeavor Medical Bay Pod": "奋进号 医疗舱吊舱",
    "Endeavor Telescope Array Bay Pod": "奋进号 望远镜阵列吊舱",
    # --- Consolidated Outland ---
    "Mustang Alpha": "野马 阿尔法",
    "Mustang Alpha Vindicator": "野马 阿尔法 惩戒者",
    "Mustang Beta": "野马 贝塔",
    "Mustang Delta": "野马 德尔塔",
    "Mustang Gamma": "野马 伽马",
    "Mustang Omega": "野马 欧米茄",
    "HoverQuad": "悬浮四轮",
    "Nomad": "游牧民",
    "Tiburon": "蒂布龙",
    # --- Esperia ---
    "Blade": "冲击刃",
    "Glaive": "战镰",
    "Scythe": "镰刀",
    "Prowler": "徘徊者",
    "Prowler Utility": "徘徊者 实用型",
    "Talon": "利爪",
    "Talon Shrike": "利爪 百舌鸟",
    # --- Xi'an / Gatac ---
    "Khartu-al": "卡图",
    "San tok.Yāi": "三得·亚伊",
    "Nox": "毒液",
    "Nox Kue": "毒液 库",
    "Syulen": "舒伦",
    "Railen": "瑞伦",
    # --- Banu ---
    "Merchantman": "巴努商船",
    "Defender": "防御者",
    # --- Tumbril ---
    "Cyclone": "气旋",
    "Cyclone AA": "气旋 防空型",
    "Cyclone MT": "气旋 军用型",
    "Cyclone RC": "气旋 遥控型",
    "Cyclone RN": "气旋 侦察型",
    "Cyclone TR": "气旋 运输型",
    "Nova Tank": "新星坦克",
    "Lynx": "猞猁",
    "STV": "STV",
    "Ironclad": "铁甲",
    "Ironclad Assault": "铁甲 突击型",
    "Shiv": "匕首",
    # --- Argo ---
    "MPUV Cargo": "MPUV 货运",
    "MPUV Personnel": "MPUV 客运",
    "MPUV Tractor": "MPUV 牵引",
    "SRV": "标准救援船",
    "RAFT": "木筏",
    # --- Greycat ---
    "ROC": "ROC",
    "ROC-DS": "ROC-DS",
    "PTV": "PTV",
    "UTV": "UTV",
    "MTC": "MTC",
    "MDC": "MDC",
    "ATLS": "ATLS",
    "ATLS GEO": "ATLS GEO",
    "ATLS IKTI": "ATLS IKTI",
    "ATLS IKTI GEO": "ATLS IKTI GEO",
    "ATLS IKTI GEO Rad": "ATLS IKTI GEO Rad",
    "ATLS IKTI Rad": "ATLS IKTI Rad",
    "CSV-FM": "CSV-FM",
    "CSV-SM": "CSV-SM",
    "G12": "G12",
    "G12-A": "G12-A",
    "G12-R": "G12-R",
    # --- Mirai ---
    "Fury": "狂怒",
    "Fury LX": "狂怒 LX",
    "Fury MX": "狂怒 MX",
    "Pulse": "脉冲",
    "Pulse LX": "脉冲 LX",
    # --- Crusader (ships) ---
    "Ares Inferno Starfighter": "战神 地狱火 星际战斗机",
    "Ares Ion Starfighter": "战神 离子光 星际战斗机",
    # --- Anvil (ground) ---
    "Storm": "风暴",
    "Storm AA": "风暴 防空型",
    # --- RSI (snubs) ---
    "P-52 Merlin": "P-52 梅林",
    "P-72 Archimedes": "P-72 阿基米德",
    "P-72 Archimedes Emerald": "P-72 阿基米德 翡翠版",
    # --- Ground vehicles ---
    "Ursa": "大熊",
    "Ursa Fortuna": "大熊 幸运",
    "Ursa Medivac": "大熊 医疗",
    "X1": "X1",
    "X1 Force": "X1 武力",
    "X1 Velocity": "X1 速度",
    "M50": "M50",
    "M80": "M80",
    "Ranger CV": "骑手 CV",
    "Ranger RC": "骑手 RC",
    "Ranger TR": "骑手 TR",
    "Carrack": "克拉克",
    "Carrack Expedition": "克拉克 远征版",
    "Crucible": "坩埚",
    "Intrepid": "无畏",
    "Galaxy": "银河",
    "Galaxy Cargo Module": "银河 货舱模块",
    "Galaxy Medical Module": "银河 医疗模块",
    "Galaxy Refinery Module": "银河 精炼模块",
    "Orion": "猎户座",
    "Clipper": "快船",
    "Scorpius": "天蝎座",
    "Scorpius Antares": "天蝎座 心宿二",
    "Arrastra": "阿拉斯塔",
    "Auxilia": "辅助者",
    "Hermes": "赫尔墨斯",
    "Meteor": "流星",
    "MOTH": "飞蛾",
    "MOLE": "鼹鼠",
    "MOLE Carbon Edition": "鼹鼠 碳纤维版",
    "MOLE Talus Edition": "鼹鼠 跖骨版",
    "Odin": "奥丁",
}


def get_vehicle_zh(en_name: str) -> str:
    """Translate vehicle name to Chinese."""
    return VEHICLE_ZH_MAP.get(en_name, en_name)


def format_location_zh(name: str, nickname: str, station: str,
                       planet: str, system: str) -> str:
    """Generate Chinese location description."""
    zh_name = get_terminal_zh(name, nickname, station, planet, system)
    parts = [zh_name]
    if planet:
        zh_planet = PLANET_ZH.get(planet, planet)
        parts.append(f"[{zh_planet}]")
    zh_system = SYSTEM_ZH.get(system, system)
    parts.append(f"({zh_system})")
    return " ".join(parts)
