export const LOCATION_KEY_MAP = {
  'Ore_Agricium': 'Agricium_Ore',
  'Ore_Aluminum': 'Aluminum',
  'Ore_Borase': 'Borase_Ore',
  'Ore_Copper': 'Copper_Ore',
  'Ore_Gold': 'Gold_Ore',
  'Ore_Iron': 'Iron_Ore',
  'Ore_Lindinium': 'Lindinium',
  'Ore_Riccite': 'Riccite_Ore',
  'Ore_Savrilium': 'Savrilium',
  'Ore_Stileron': 'Stileron',
  'Ore_Tin': 'Tin_Ore',
  'Ore_Titanium': 'Titanium_Ore',
  'Ore_Torite': 'Torite_Ore',
  'Ore_Tungsten': 'Tungsten_Ore',
  'Ore_Jaclium': 'Jaclium',
  'Ore_Saldynium': 'Saldynium',
  'Aluminium_Ore': 'Aluminum',
  'Ice_Raw': 'Raw Ice',
  'RawOuratite': 'Raw Ouratite',
  'RawSilicon': 'Raw Silicon',
  'Raw_Aslarite': 'Aslarite_Raw',
  'Raw_Beryl': 'Beryl_Raw',
  'Raw_Bexalite': 'Bexalite_Raw',
  'Raw_Corundum': 'Corundum_Raw',
  'Raw_Hephaestanite': 'Hephaestanite_Raw',
  'Raw_Ice': 'Raw Ice',
  'Raw_Laranite': 'Laranite_Raw',
  'Raw_Quantainium': 'Quantainium_Raw',
  'Raw_Quartz': 'Quartz_Raw',
  'Raw_Taranite': 'Taranite_Raw',
  'MinableElement_FPS_Aphorite': 'MinableElement_FPS_Aphorite',
  'MinableElement_FPS_Dolivine': 'MinableElement_FPS_Dolivine',
  'MinableElement_FPS_Hadanite': 'MinableElement_FPS_Hadanite',
  'MinableElement_FPS_Janalite': 'MinableElement_FPS_Janalite',
  'MinableElement_FPS_Carinite': 'Carinite',
  'MinableElement_FPS_CarinitePure': 'CarinitePure',
  'MinableElement_FPS_Flowstone': 'Flowstone',
  'MinableElement_FPS_Sadaryx': 'Sadaryx',
  'MinableElement_FPS_Saldynium': 'Saldynium',
  'MinableElement_FPS_VLKLimpet': 'Vlk_Limpet',
  'MinableElement_GroundVehicle_Beradom': 'MinableElement_GroundVehicle_Beradom',
  'MinableElement_GroundVehicle_Feynmaline': 'MinableElement_GroundVehicle_Feynmaline',
  'MinableElement_GroundVehicle_Glacosite': 'MinableElement_GroundVehicle_Glacosite',
  'MinableElement_GroundVehicle_Carinite': 'Carinite',
  'Diamond_Raw': 'Diamond',
  'Lindinium_Ore': 'Lindinium',
  'Ouratite_Raw': 'Raw Ouratite',
  'Riccite_Ore': 'Riccite',
  'Savrilium_Ore': 'Savrilium',
  'Sileron_Ore': 'Stileron',
  'Silicon_Raw': 'Raw Silicon',
  'Aphorite': 'MinableElement_FPS_Aphorite',
  'Beradom': 'MinableElement_GroundVehicle_Beradom',
  'Dolivine': 'MinableElement_FPS_Dolivine',
  'Feynmaline': 'MinableElement_GroundVehicle_Feynmaline',
  'Glacosite': 'MinableElement_GroundVehicle_Glacosite',
  'Hadanite': 'MinableElement_FPS_Hadanite',
  'Janalite': 'MinableElement_FPS_Janalite',
};

export function rawNameToLocationKey(rawName) {
  return LOCATION_KEY_MAP[rawName] || rawName;
}
